### ISSUE TITLE
Exact usage of 'way num' and 'test way'

### ISSUE THREAD

**Issue by seygodin** [RL-VIG/LibFewShot#69]
Hello, I'm a junior deep learning researcher.

I'm using this library so well. By the way, I was testing a dataset with 10 classes and selected the 'way_num' and 'test_way' into 5 my mistake. There wasn't, however, an error. I saw the code and the two variables below are used for the layer. I guessed according to the num setting the result will be changed.

https://github.com/RL-VIG/LibFewShot/issues/54#issuecomment-1266532642

I was looking for a solution and found that answer in the issue of this repository. That says "if there are only 4 classes in your dataset, you should set way_num <=4". I thought that the number way_num is decided on N-way-M shot problem by the composition of a dataset. Would you explain the meaning and usage of "way_num" and how does it work while calculating accuracy?

Thank you so much.

**Comment by yangcedrus** [comment]
Hi.

Maybe you're a little wrong about the `way_num` in few-shot learning.

`way_num`: the N of N-way K-shot during traing
`test_way`: the N of N-way K-shot during validation and testing
Neither of above two is related to the composition of dataset. N refers to the number of classes **that need to be sampled from the dataset** rather than the number of classes in the dataset

In few-shot leaning, dataset is divided into 3 parts: `train`, `val` and `test` with different number of classes or the same sometimes. A train task with way_num classes will be sampled from train set, so the `way_num must <= trainset_class_num`. Val and test are the same.
