### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by rajivchoudhury** [RL-VIG/LibFewShot#76]
ImportError: cannot import name 'Iterable' from 'collections' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\collections\__init__.py)

Error is shown when running run_trainner.py

**Comment by wZuck** [comment]
This error is not caused by LibFewShot. You can replace https://github.com/RL-VIG/LibFewShot/blob/eb68580c12c524a944242d236af223ff71465c75/core/data/collates/collate_functions.py#L3 with `from collections.abc import Iterable`.

For more information, please refer to [stackoverflow](https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python).
